const pages={dashboard:['Dashboard','Here’s your signal business overview.'],signals:['Signal Center','Create, manage and track all your signals.'],copy:['Copy Trade','Manage your copy trading business and capacity.'],subscribers:['Subscribers','Manage your signal subscribers and access.'],reports:['Reports & Analytics','Track your performance and business growth.'],branding:['Settings & Branding','Customize your brand identity and appearance.'],settings:['Settings','Manage workspace connections and configuration.']};
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===id));document.getElementById('pageTitle').textContent=pages[id][0];document.getElementById('pageSubtitle').textContent=pages[id][1];requestAnimationFrame(drawAll)}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
const signals=[['XAUUSD','BUY','2034.50','2045.00','2028.00','Active','—','2h ago'],['EURUSD','SELL','1.0850','1.0780','1.0900','TP Hit','+$160','5h ago'],['BTCUSDT','BUY','43250','44500','42000','TP Hit','+$320','8h ago'],['SOLUSDT','BUY','98.50','105.00','95.00','Active','—','12h ago'],['GBPUSD','SELL','1.2720','1.2650','1.2780','SL Hit','-$110','1d ago'],['ETHUSDT','BUY','2650','2750','2600','Closed','+$200','1d ago'],['XRPUSDT','SELL','0.5840','0.5600','0.6000','Closed','+$150','1d ago']];
document.querySelector('#signalTable tbody').innerHTML=signals.map(r=>`<tr><td><b>${r[0]}</b></td><td><em class="${r[1]==='BUY'?'buy':'sell'}">${r[1]}</em></td>${r.slice(2,5).map(x=>`<td>${x}</td>`).join('')}<td><span class="status">${r[5]}</span></td><td class="${r[6].startsWith('+')?'positive':r[6].startsWith('-')?'negative':''}">${r[6]}</td><td>${r[7]}</td></tr>`).join('');
const subscribers=[['trader_pro','VIP','2026-08-10','2026-10-10','Active','Active'],['gold_master','VIP','2026-08-14','2026-10-14','Active','Active'],['crypto_whale','VIP','2026-08-18','2026-10-18','Active','Active'],['forex_trader','Free','2026-08-20','—','Active','Off'],['nexus_user','VIP','2026-08-22','2026-10-22','Active','Active'],['scalp_king','VIP','2026-08-25','2026-10-25','Active','Active']];document.getElementById('subscriberTable').innerHTML=subscribers.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td><span class="status">${r[4]}</span></td><td>${r[5]}</td></tr>`).join('');
function setup(canvas){if(!canvas||canvas.offsetParent===null)return null;const dpr=window.devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);return{c,w,h}}
function lineChart(id,data,fill=true){const x=setup(document.getElementById(id));if(!x)return;const{c,w,h}=x,p={l:40,r:15,t:15,b:30};c.clearRect(0,0,w,h);c.font='11px system-ui';c.strokeStyle='#e9eef5';c.fillStyle='#8492a5';for(let i=0;i<5;i++){const y=p.t+(h-p.t-p.b)*i/4;c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke()}const max=Math.max(...data)*1.15,min=Math.min(...data)*.8;const pts=data.map((v,i)=>[p.l+(w-p.l-p.r)*i/(data.length-1),p.t+(h-p.t-p.b)*(1-(v-min)/(max-min))]);if(fill){const g=c.createLinearGradient(0,p.t,0,h-p.b);g.addColorStop(0,'rgba(47,114,255,.22)');g.addColorStop(1,'rgba(47,114,255,0)');c.beginPath();c.moveTo(pts[0][0],h-p.b);pts.forEach(q=>c.lineTo(...q));c.lineTo(pts.at(-1)[0],h-p.b);c.closePath();c.fillStyle=g;c.fill()}c.beginPath();pts.forEach((q,i)=>i?c.lineTo(...q):c.moveTo(...q));c.strokeStyle='#2f72ff';c.lineWidth=2.4;c.stroke();pts.forEach(q=>{c.beginPath();c.arc(q[0],q[1],3,0,Math.PI*2);c.fillStyle='#fff';c.fill();c.strokeStyle='#2f72ff';c.stroke()})}
function donut(id,values){const x=setup(document.getElementById(id));if(!x)return;const{c,w,h}=x,colors=['#2f72ff','#14c9b7','#ffad32','#ef5a62','#8ba4c7'],total=values.reduce((a,b)=>a+b,0),r=Math.min(w,h)*.38;let a=-Math.PI/2;values.forEach((v,i)=>{const n=a+Math.PI*2*v/total;c.beginPath();c.arc(w/2,h/2,r,a,n);c.strokeStyle=colors[i];c.lineWidth=25;c.stroke();a=n})}
function pnlChart(){const canvas=document.getElementById('pnlChart'),x=setup(canvas);if(!x)return;const{c,w,h}=x,data=[420,650,-230,820,510,-480,930,740,-310,1050,610,880,-560,1200],p={l:42,r:20,t:20,b:30},mid=(h-p.b+p.t)/2,max=1300;c.strokeStyle='#e9eef5';for(let i=0;i<5;i++){const y=p.t+(h-p.t-p.b)*i/4;c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke()}const bw=(w-p.l-p.r)/data.length*.55;data.forEach((v,i)=>{const x0=p.l+(i+.5)*(w-p.l-p.r)/data.length,y=mid-(v/max)*(h-p.t-p.b)*.42;c.fillStyle=v>=0?'#13b981':'#ef8a42';c.fillRect(x0-bw/2,Math.min(mid,y),bw,Math.abs(mid-y))})}
function drawAll(){lineChart('revenueChart',[2.1,2.9,3.6,3.3,4.4,4.8,5.6,5.2,6.1,6.5,6.0,6.24]);donut('signalDonut',[35,28,22,10,5]);lineChart('copyChart',[110,145,132,178,190,220,238,260,275,310,330,342]);pnlChart()}
window.addEventListener('resize',()=>requestAnimationFrame(drawAll));drawAll();