(() => {
  const DEFAULTS={primary_color:'#2F72FF',secondary_color:'#14C9B7',accent_color:'#FFAD32',background_color:'#07172A'};
  let current=null;

  function auth(){const params=new URLSearchParams(location.search);return{tenantId:params.get('tenant_id')||sessionStorage.getItem('provider_tenant_id'),initData:window.Telegram?.WebApp?.initData||''}}
  function headers(){const a=auth();return{'Content-Type':'application/json','X-Telegram-Init-Data':a.initData,'X-Tenant-Id':a.tenantId}}
  function editableNodes(){const page=document.getElementById('branding');if(!page)return{};const preview=page.querySelector('.preview-banner');const labels=[...page.querySelectorAll('.colors label b')];return{page,save:page.querySelector('.section-head .primary'),brand:preview?.querySelector('strong'),tagline:preview?.querySelector('p'),preview,logo:page.querySelector('.provider-logo'),favicon:page.querySelector('.favicon'),labels,uploads:[...page.querySelectorAll('.upload')]}}
  function assetNode(node,url,fallback){if(!node)return;node.replaceChildren();if(url){const img=document.createElement('img');img.src=url;img.alt='Provider brand asset';img.style.cssText='width:100%;height:100%;object-fit:cover;border-radius:inherit';node.appendChild(img)}else node.textContent=fallback}
  function applyBranding(data){current={...DEFAULTS,...data};const n=editableNodes();if(!n.page)return;if(n.brand)n.brand.textContent=current.brand_name||'Provider';if(n.tagline)n.tagline.textContent=current.tagline||'Trade Smarter. Together.';n.labels.forEach((b,i)=>{b.textContent=[current.primary_color,current.secondary_color,current.accent_color,current.background_color][i]});const colorDots=n.page.querySelectorAll('.colors label i');[current.primary_color,current.secondary_color,current.accent_color,current.background_color].forEach((c,i)=>{if(colorDots[i])colorDots[i].style.background=c});if(n.preview){n.preview.style.background=current.background_color;n.preview.style.setProperty('--provider-primary',current.primary_color)}const initial=(current.brand_name||'P').trim().charAt(0).toUpperCase();assetNode(n.logo,current.logo_url,initial);assetNode(n.favicon,current.favicon_url,initial);const sidebarMark=document.querySelector('.brand-mark');if(sidebarMark){sidebarMark.style.background=current.primary_color;sidebarMark.textContent=initial}document.documentElement.style.setProperty('--provider-primary',current.primary_color)}
  function enableEditing(){const n=editableNodes();if(!n.page)return;if(n.brand)n.brand.contentEditable='true';if(n.tagline)n.tagline.contentEditable='true';n.labels.forEach(b=>{b.contentEditable='true';b.spellcheck=false});n.uploads.forEach((box,i)=>{box.style.cursor='pointer';box.title=i===0?'Click to set logo URL':'Click to set favicon URL';box.addEventListener('click',()=>{const key=i===0?'logo_url':'favicon_url';const next=window.prompt(i===0?'Logo URL (https://... or /path)':'Favicon URL (https://... or /path)',current?.[key]||'');if(next!==null){current={...(current||DEFAULTS),[key]:next.trim()||null};applyBranding(current)}})});n.save?.addEventListener('click',save)}
  function payload(){const n=editableNodes();return{brand_name:n.brand?.textContent?.trim()||null,tagline:n.tagline?.textContent?.trim()||null,primary_color:n.labels[0]?.textContent?.trim()||DEFAULTS.primary_color,secondary_color:n.labels[1]?.textContent?.trim()||DEFAULTS.secondary_color,accent_color:n.labels[2]?.textContent?.trim()||DEFAULTS.accent_color,background_color:n.labels[3]?.textContent?.trim()||DEFAULTS.background_color,logo_url:current?.logo_url||null,favicon_url:current?.favicon_url||null}}
  async function save(){const a=auth();if(!a.tenantId||!a.initData)return;const n=editableNodes();const original=n.save?.textContent;if(n.save)n.save.textContent='Saving…';try{const response=await fetch('/provider/api/branding',{method:'PUT',headers:headers(),body:JSON.stringify(payload())});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`branding ${response.status}`)}const result=await response.json();applyBranding(result.branding||{});if(n.save)n.save.textContent='Saved'}catch(error){console.warn('Provider branding save failed',error);if(n.save)n.save.textContent='Save failed'}finally{setTimeout(()=>{if(n.save)n.save.textContent=original||'Save Changes'},1400)}}
  async function load(){enableEditing();const a=auth();if(!a.tenantId||!a.initData)return;try{const response=await fetch('/provider/api/branding',{headers:headers()});if(!response.ok)throw new Error(`branding ${response.status}`);const result=await response.json();applyBranding(result.branding||{})}catch(error){console.warn('Provider branding unavailable; preview retained.',error)}}
  load();
})();
