import{useEffect,useMemo,useState}from'react';
import{Activity,BarChart3,Bot,CircleDollarSign,Headphones,Home,RefreshCw,Settings,Shield,Users,Zap}from'lucide-react';

type J=Record<string,any>; type Page='home'|'signals'|'trade'|'plans'|'support'|'admin';
const tg=window.Telegram?.WebApp;
async function api(path:string,options:RequestInit={}){const h=new Headers(options.headers);h.set('Content-Type','application/json');if(tg?.initData)h.set('X-Telegram-Init-Data',tg.initData);const r=await fetch('/api/v1/miniapp'+path,{...options,headers:h});if(!r.ok){let m='خطا در ارتباط';try{m=(await r.json()).detail||m}catch{}throw new Error(m)}return r.status===204?null:r.json()}
const fmt=(v:any)=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:2}).format(Number(v||0));
const dt=(v:any)=>v?new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium'}).format(new Date(v)):'—';

function Card({title,children,className=''}:{title?:string;children:any;className?:string}){return <section className={'card '+className}>{title&&<h3>{title}</h3>}{children}</section>}
function Badge({value}:{value:any}){const s=String(value||'—').toUpperCase();return <span className={'badge '+(s.includes('ACTIVE')||s.includes('OPEN')||s.includes('APPROVED')?'ok':s.includes('PENDING')?'wait':s.includes('CLOSE')||s.includes('REJECT')||s.includes('BLOCK')?'bad':'')}>{s}</span>}
function Empty(){return <div className="empty">داده‌ای برای نمایش وجود ندارد</div>}

export default function App(){
 const[page,setPage]=useState<Page>('home'),[session,setSession]=useState<J|null>(null),[data,setData]=useState<J|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{tg?.ready();tg?.expand();loadSession()},[]);
 async function loadSession(){setBusy(true);setError('');try{setSession(await api('/session'))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function go(p:Page){setPage(p);setData(null);setError('');if(p==='home')return loadSession();setBusy(true);try{setData(await api(p==='signals'?'/signals':p==='trade'?'/autotrade':p==='plans'?'/commerce':p==='support'?'/support':'/admin/data'))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function toast(msg:string){tg?.HapticFeedback?.impactOccurred('light');setError(msg);setTimeout(()=>setError(''),2600)}
 if(!session&&!busy)return <main className="gate"><div className="brandmark">N</div><h1>NEXUS</h1><p>{error||'این مینی‌اپ را از داخل ربات NEXUS باز کنید.'}</p><button onClick={loadSession}>تلاش دوباره</button></main>;
 return <div className="app"><header><div><small>NEXUS AUTO TRADE</small><h1>سلام، {session?.user?.first_name||'کاربر'}</h1></div><button className="icon" onClick={()=>go(page)} aria-label="بروزرسانی"><RefreshCw size={18}/></button></header>
  {error&&<div className="toast">{error}</div>}{busy&&<div className="loading"/>}
  <main>{page==='home'&&session&&<HomePage s={session} go={go}/>} {page==='signals'&&data&&<Signals d={data}/>} {page==='trade'&&data&&<Trade d={data} reload={()=>go('trade')} toast={toast}/>} {page==='plans'&&data&&<Plans d={data} s={session!}/>} {page==='support'&&data&&<Support d={data} reload={()=>go('support')} toast={toast}/>} {page==='admin'&&data&&<Admin d={data} reload={()=>go('admin')} toast={toast}/>}</main>
  <nav>{([['home',Home,'خانه'],['signals',BarChart3,'سیگنال'],['trade',Bot,'اتو ترید'],['plans',CircleDollarSign,'اشتراک'],['support',Headphones,'پشتیبانی']]as any[]).map(([p,I,l])=><button className={page===p?'active':''} onClick={()=>go(p)} key={p}><I size={20}/><span>{l}</span></button>)}</nav></div>
}

function HomePage({s,go}:{s:J;go:(p:Page)=>void}){const active=s.entitlements.vip||s.entitlements.autotrade;return <><Card className="hero"><div className="heroTop"><div><small>وضعیت حساب</small><h2>{active?'اشتراک فعال':'حساب رایگان'}</h2></div><Badge value={active?'ACTIVE':'FREE'}/></div><div className="metrics"><div><b>{fmt(s.referral.points)}</b><span>امتیاز</span></div><div><b>{s.level?.fa||'Bronze'}</b><span>سطح</span></div><div><b>{s.mt5?'متصل':'قطع'}</b><span>MT5</span></div></div></Card>
 <div className="grid2"><button className="quick" onClick={()=>go('signals')}><Zap/><b>سیگنال‌ها</b><span>فرصت‌های فعال</span></button><button className="quick" onClick={()=>go('trade')}><Activity/><b>معاملات من</b><span>وضعیت زنده</span></button></div>
 <Card title="دسترسی‌ها"><div className="rows"><div><span>کانال VIP</span><Badge value={s.entitlements.vip?'ACTIVE':'LOCKED'}/></div><div><span>AutoTrade</span><Badge value={s.entitlements.autotrade?'ACTIVE':'LOCKED'}/></div><div><span>انقضا</span><b>{dt(s.license?.expires_at)}</b></div></div></Card>
 {s.user.is_admin&&<button className="adminEntry" onClick={()=>go('admin')}><Shield/>ورود به مدیریت مینی‌اپ</button>}</>}

function Signals({d}:{d:J}){return <><div className="title"><h2>سیگنال‌ها</h2><span>{d.items.length} مورد</span></div>{d.items.length?d.items.map((x:J)=><Card key={x.id} className="signal"><div className="signalHead"><div><b>{x.symbol}</b><small>{x.code} · {x.timeframe}</small></div><Badge value={x.status}/></div><div className="priceGrid"><div><span>جهت</span><b className={x.direction==='BUY'?'buy':'sell'}>{x.direction}</b></div><div><span>ورود</span><b>{x.entry_price}</b></div><div><span>حد ضرر</span><b>{x.stop_loss}</b></div></div><div className="targets">{x.targets.map((t:J)=><span key={t.target_no}>TP{t.target_no} <b>{t.price}</b></span>)}</div><footer><span>{x.trailing_code||'بدون تریلینگ'}</span><span>{dt(x.created_at)}</span></footer></Card>):<Empty/>}</>}

function Trade({d,reload,toast}:{d:J;reload:()=>void;toast:(x:string)=>void}){const[r,setR]=useState({...d.risk,emergency_stop:!!d.risk.emergency_stop});async function save(){try{await api('/risk',{method:'PUT',body:JSON.stringify(r)});toast('تنظیمات ذخیره شد');reload()}catch(e:any){toast(e.message)}}return <><div className="title"><h2>AutoTrade</h2><Badge value={d.account?'CONNECTED':'OFFLINE'}/></div><div className="metrics top"><div><b>{fmt(d.today.net_pnl)}$</b><span>سود امروز</span></div><div><b>{fmt(d.open.length)}</b><span>باز</span></div><div><b>{fmt(d.today.closed)}</b><span>بسته</span></div></div><Card title="مدیریت ریسک"><label>مرجع تنظیمات<select value={r.management_mode} onChange={e=>setR({...r,management_mode:e.target.value})}><option value="SELF">تنظیم شخصی</option><option value="ADMIN">اختیار ادمین</option></select></label><div className="form2"><label>ریسک هر معامله<input type="number" step=".1" value={r.risk_percent} onChange={e=>setR({...r,risk_percent:+e.target.value})}/></label><label>حد زیان روزانه<input type="number" value={r.max_daily_loss} onChange={e=>setR({...r,max_daily_loss:+e.target.value})}/></label><label>حداکثر معاملات باز<input type="number" value={r.max_open_trades} onChange={e=>setR({...r,max_open_trades:+e.target.value})}/></label><label>حداکثر معاملات روزانه<input type="number" value={r.max_daily_trades} onChange={e=>setR({...r,max_daily_trades:+e.target.value})}/></label></div><label className="switch"><input type="checkbox" checked={r.emergency_stop} onChange={e=>setR({...r,emergency_stop:e.target.checked})}/><span>توقف اضطراری معاملات جدید</span></label><button onClick={save}>ذخیره تنظیمات</button></Card><Card title="معاملات باز">{d.open.length?d.open.map((x:J)=><div className="tradeRow" key={x.ticket}><div><b>{x.symbol}</b><small>#{x.ticket}</small></div><Badge value={x.status}/></div>):<Empty/>}</Card></>}

function Plans({d,s}:{d:J;s:J}){const[selected,setSelected]=useState('');const[method,setMethod]=useState<'CARD'|'USDT'>('USDT');const[ref,setRef]=useState('');const[msg,setMsg]=useState('');async function submit(){if(!selected||ref.trim().length<4)return setMsg('پلن و کد پیگیری را وارد کنید');try{await api('/payments',{method:'POST',body:JSON.stringify({plan_code:selected,method,reference:ref})});setMsg('پرداخت برای بررسی ادمین ثبت شد');setRef('')}catch(e:any){setMsg(e.message)}}return <><div className="title"><h2>اشتراک</h2><Badge value={s.license?.status||'FREE'}/></div>{d.plans.map((p:J)=><Card key={p.code} className="plan"><div><small>{p.service_type==='auto_trade'?'AUTO TRADE':'VIP SIGNAL'}</small><h3>{p.fa||p.en||p.code}</h3><p>{p.days} روز دسترسی</p></div><div className="planPrice"><b>{p.price_usdt}</b><span>USDT</span></div><button onClick={()=>setSelected(p.code)}>انتخاب</button></Card>)}<Card title="ثبت پرداخت"><label>روش پرداخت<select value={method} onChange={e=>setMethod(e.target.value as any)}><option value="USDT">تتر ({d.payment.usdt_network})</option><option value="CARD">کارت بانکی</option></select></label><div className="paymentBox">{method==='USDT'?<><small>آدرس کیف پول</small><b>{d.payment.usdt_wallet||'توسط ادمین تنظیم نشده'}</b></>:<><small>شماره کارت به نام {d.payment.owner}</small><b>{d.payment.card}</b></>}</div><label>پلن<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">انتخاب کنید</option>{d.plans.map((p:J)=><option value={p.code}>{p.fa||p.code}</option>)}</select></label><label>هش تراکنش / کد پیگیری<input value={ref} onChange={e=>setRef(e.target.value)} placeholder="کد قابل بررسی"/></label><button className="primary" onClick={submit}>ثبت برای تأیید ادمین</button>{msg&&<p>{msg}</p>}</Card><Card title="پرداخت‌های من">{d.payments.length?d.payments.map((p:J)=><div className="tradeRow" key={p.id}><div><b>{p.plan_code}</b><small>{dt(p.created_at)}</small></div><Badge value={p.status}/></div>):<Empty/>}</Card></>}

function Support({d,reload,toast}:{d:J;reload:()=>void;toast:(x:string)=>void}){const[f,setF]=useState({subject:'',message:'',priority:'NORMAL'});async function send(){try{await api('/support',{method:'POST',body:JSON.stringify(f)});setF({subject:'',message:'',priority:'NORMAL'});toast('درخواست ثبت شد');reload()}catch(e:any){toast(e.message)}}return <><div className="title"><h2>پشتیبانی</h2></div><Card title="درخواست جدید"><label>موضوع<input value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/></label><label>پیام<textarea rows={4} value={f.message} onChange={e=>setF({...f,message:e.target.value})}/></label><button onClick={send}>ارسال درخواست</button></Card>{d.items.map((x:J)=><Card key={x.id}><div className="signalHead"><b>{x.subject}</b><Badge value={x.status}/></div><p>{x.message}</p>{x.admin_reply&&<div className="reply">پاسخ: {x.admin_reply}</div>}</Card>)}</>}

function Admin({d,reload,toast}:{d:J;reload:()=>void;toast:(x:string)=>void}){const[tab,setTab]=useState<'users'|'payments'|'signals'|'changes'|'audit'>('users');async function act(path:string,body:J){try{await api(path,{method:'POST',body:JSON.stringify(body)});toast('عملیات ثبت شد');reload()}catch(e:any){toast(e.message)}}const list=useMemo(()=>d[tab]||[],[d,tab]);return <><div className="title"><h2>مدیریت</h2><Shield/></div><div className="adminTabs">{([['users','کاربران'],['payments','پرداخت'],['signals','سیگنال'],['changes','حساب MT5'],['audit','رویداد']]as any[]).map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>{!list.length?<Empty/>:list.map((x:J)=><Card key={tab+(x.id||x.telegram_id)}><div className="signalHead"><div><b>{tab==='users'?(x.first_name||x.username||x.telegram_id):tab==='payments'?x.plan_code:tab==='signals'?(x.code+' · '+x.symbol):tab==='changes'?(x.old_account_number+' ← '+x.new_account_number):x.action}</b><small>{dt(x.created_at||x.requested_at)}</small></div><Badge value={x.status}/></div>{tab==='users'&&<div className="actions"><button onClick={()=>act(`/admin/users/${x.telegram_id}/action`,{action:'EXTEND',value:30})}>+۳۰ روز</button><button onClick={()=>act(`/admin/users/${x.telegram_id}/action`,{action:'ADD_POINTS',value:100})}>+۱۰۰ امتیاز</button><button className="danger" onClick={()=>act(`/admin/users/${x.telegram_id}/action`,{action:'BLOCK',value:1})}>مسدود</button></div>}{tab==='payments'&&x.status==='pending'&&<div className="actions"><button onClick={()=>act(`/admin/payments/${x.id}/review`,{approve:true})}>تأیید</button><button className="danger" onClick={()=>act(`/admin/payments/${x.id}/review`,{approve:false})}>رد</button></div>}{tab==='changes'&&<div className="actions"><button onClick={()=>act(`/admin/account-changes/${x.id}/review`,{approve:true})}>تأیید</button><button className="danger" onClick={()=>act(`/admin/account-changes/${x.id}/review`,{approve:false})}>رد</button></div>}</Card>)}</>}
