(() => {
  const tg=window.Telegram?.WebApp; tg?.ready(); tg?.expand();
  const API='/miniapp/api/admin';
  const state={side:'BUY',destination:'BOTH',setupMode:'MANUAL',volumeMode:'RISK',calculation:null,mt5:null,preview:null};
  const $=id=>document.getElementById(id);
  const headers=()=>({'Content-Type':'application/json',...(tg?.initData?{'X-Telegram-Init-Data':tg.initData}:{})});
  async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||'خطا در ارتباط با سرور');return b}
  function toast(m){$('toast').textContent=m;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
  function fa(v){return new Intl.NumberFormat('fa-IR',{maximumFractionDigits:8}).format(Number(v||0))}
  function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
  function signed(v,d=2){const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}${n.toFixed(d)}`:'—'}
  function pulse(status){const s=String(status||'UNAVAILABLE').toLowerCase();return `<span class="admin-live-pulse ${esc(s)}" aria-hidden="true"><svg viewBox="0 0 64 48"><polyline class="pulse-back" points="0.157 23.954, 14 23.954, 21.843 48, 43 0, 50 24, 64 24"></polyline><polyline class="pulse-front" points="0.157 23.954, 14 23.954, 21.843 48, 43 0, 50 24, 64 24"></polyline></svg></span>`}
  function liveBlock(l){if(!l)return'';const s=String(l.status||'UNAVAILABLE').toUpperCase(),p=String(l.pnl_state||'').toLowerCase(),sync=l.age_seconds!=null?`${Math.round(Number(l.age_seconds))}s ago`:'—',label=s==='LIVE'?'MT5 LIVE':s==='PENDING'?'MT5 PENDING':s==='STALE'?'STALE':'LIVE DATA UNAVAILABLE';if(s==='UNAVAILABLE')return `<div class="admin-live unavailable"><div class="admin-live-head">${pulse(s)}<b>${label}</b><small>—</small></div></div>`;return `<div class="admin-live ${esc(s.toLowerCase())}"><div class="admin-live-head">${pulse(s)}<b>${label}</b><small>${esc(sync)}</small></div><div class="admin-live-grid"><span>CURRENT<b>${esc(l.current_price??'—')}</b></span><span>FLOATING P&amp;L<b class="${esc(p)}">${signed(l.floating_pnl)}</b></span><span>CURRENT R<b>${l.current_r==null?'—':signed(l.current_r)+'R'}</b></span><span>VOLUME<b>${esc(l.volume??'—')}</b></span><span>LIVE SL<b>${esc(l.stop_loss??'—')}</b></span><span>LIVE TP<b>${esc(l.take_profit??'—')}</b></span></div></div>`}
  function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('selected',x.dataset.view===v));if(v==='positions')loadPositions();if(v==='logs')loadSignals()}
  function setMt5(m){state.mt5=m;const c=$('mt5Chip');c.className='chip '+(m?.online?'online':'offline');c.querySelector('span').textContent=m?.online?'MT5 متصل':'MT5 آفلاین'}
  async function bootstrap(){try{const d=await api('/bootstrap');setMt5(d.mt5_admin);await Promise.all([loadSignals(),loadPositions()])}catch(e){toast(e.message);$('signalList').innerHTML='<div class="empty">این صفحه فقط از داخل تلگرام و برای ادمین‌های مجاز فعال است.</div>'}}
  function syncModeUI(){const auto=state.setupMode==='AUTO';$('stopLossLabel').hidden=auto;$('stopLoss').required=!auto;$('fixedLotLabel').hidden=state.volumeMode!=='FIXED';$('lotSize').required=state.volumeMode==='FIXED';state.calculation=null;$('riskBox').querySelector('b').textContent='—';$('targets').innerHTML=`<p>${auto?'Auto Setup پس از اتصال Structure Engine محاسبه می‌شود.':'Entry و Stop Loss را وارد کنید.'}</p>`;if(!auto)recalculate()}
  async function recalculate(){if(state.setupMode==='AUTO')return;const entry=Number($('entry').value),stop=Number($('stopLoss').value);if(!entry||!stop)return;try{const c=await api('/signals/calculate',{method:'POST',body:JSON.stringify({symbol:$('symbol').value,direction:state.side,entry,stop_loss:stop})});state.calculation=c;$('riskBox').querySelector('b').textContent=fa(c.risk);$('targets').innerHTML=c.targets.map((x,i)=>`<article><small>TP${i+1} · ${c.target_multipliers[i]}R</small><b>${fa(x)}</b></article>`).join('')}catch(e){state.calculation=null;$('targets').innerHTML=`<p>${esc(e.message)}</p>`}}
  function requestId(){return `tg-${tg?.initDataUnsafe?.user?.id||'admin'}-${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`}
  function openPreview(){if(state.setupMode==='AUTO')return toast('Auto Setup تا اتصال Structure Engine اجازه انتشار ندارد.');const c=state.calculation;if(!c)return toast('ابتدا Entry و Stop Loss معتبر وارد کنید.');const lot=state.volumeMode==='FIXED'?Number($('lotSize').value):null;if(state.volumeMode==='FIXED'&&(!Number.isFinite(lot)||lot<=0))return toast('در حالت Fixed Lot وارد کردن حجم معتبر اجباری است.');state.preview={symbol:c.symbol,direction:c.direction,entry:c.entry,stop_loss:c.stop_loss,risk:c.risk,targets:c.targets,destination:state.destination,timeframe:$('timeframe').value,request_id:requestId(),digits:c.digits,setup_mode:state.setupMode,trailing_code:$('trailing').value,volume_mode:state.volumeMode,lot_size:lot};$('preview').innerHTML=`<div class="preview-hero"><strong>${esc(c.symbol)}</strong><em>${esc(c.direction)}</em></div><div class="preview-grid"><div><span>ورود</span><b>${fa(c.entry)}</b></div><div><span>حد ضرر</span><b>${fa(c.stop_loss)}</b></div><div><span>Initial R</span><b>${fa(c.risk)}</b></div><div><span>Trailing</span><b>${esc($('trailing').value)}</b></div><div><span>Volume</span><b>${esc(state.volumeMode)}${lot?' · '+esc(lot):''}</b></div>${c.targets.map((x,i)=>`<div><span>TP${i+1} · ${c.target_multipliers[i]}R</span><b>${fa(x)}</b></div>`).join('')}<div><span>وضعیت MT5 Admin</span><b>${state.mt5?.online?'ONLINE':'OFFLINE · WAITING'}</b></div></div>`;$('modal').hidden=false}
  async function publish(){if(!state.preview)return;const b=$('publish');b.disabled=true;b.textContent='در حال ثبت امن…';try{const r=await api('/signals',{method:'POST',body:JSON.stringify(state.preview)});$('modal').hidden=true;toast(r.status==='WAITING_FOR_MT5'?'ثبت شد؛ منتظر اتصال MT5 است.':'درخواست برای MT5 ارسال شد.');show('logs');await loadSignals()}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='تأیید و ارسال'}}
  function signalCard(item){const p=JSON.parse(item.payload_json||'{}'),job=String(item.chart_job?.status||'').toUpperCase(),stage=String(item.signal?.publication_stage||'').toUpperCase();const retryable=['FAILED','PUBLISH_FAILED','EXPIRED'].includes(String(item.status).toUpperCase())||(['UPLOADED','COMPLETED'].includes(job)&&item.status!=='PUBLISHED'&&stage!=='PUBLISHED');const retry=retryable?`<button class="outline retry-signal" data-request-id="${esc(item.request_id)}">تلاش مجدد</button>`:'';const entry=p.entry??item.signal?.entry_price??'—';return `<article class="card"><div class="card-head"><strong>${esc(p.symbol||item.signal?.symbol||'—')} · ${esc(p.direction||item.signal?.direction||'')}</strong><span class="status ${esc(item.status)}">${esc(item.status)}</span></div><div class="levels"><span>ENTRY<b>${esc(entry)}</b></span><span>SL<b>${esc(p.stop_loss??item.signal?.stop_loss??'—')}</b></span><span>DEST<b>${esc(p.destination||item.signal?.destination||'—')}</b></span></div>${liveBlock(item.live)}${item.error_message?`<p style="color:var(--red);font-size:10px">${esc(item.error_message)}</p>`:''}${retry}</article>`}
  async function retrySignal(button){button.disabled=true;try{const result=await api(`/signals/${encodeURIComponent(button.dataset.requestId)}/retry`,{method:'POST'});toast(result.publication==='RETRY_QUEUED'?'انتشار مجدد در صف قرار گرفت.':'درخواست همان سیگنال احیا شد.');await loadSignals()}catch(e){toast(e.message)}finally{button.disabled=false}}
  async function loadSignals(){try{const d=await api('/signals');setMt5(d.mt5_admin);$('signalList').innerHTML=d.items.length?d.items.map(signalCard).join(''):'<div class="empty">هنوز سیگنالی صادر نشده است.</div>';$('logList').innerHTML=d.items.length?d.items.map(signalCard).join(''):'<div class="empty">لاگی وجود ندارد.</div>';$('openCount').textContent=fa(d.items.filter(x=>!['PUBLISHED','FAILED'].includes(x.status)).length);$('waitingCount').textContent=fa(d.items.filter(x=>x.status==='WAITING_FOR_MT5').length)}catch(e){toast(e.message)}}
  function positionCard(p,isOrder=false){const signalId=Number(p.signal_id||0),account=esc(state.mt5?.account_number||''),profit=Number(p.profit||0),age=p.last_seen_at?Math.max(0,Math.round((Date.now()-new Date(p.last_seen_at).getTime())/1000)):null;const actions=signalId?`<div class="trade-actions" data-signal="${signalId}" data-account="${account}">${isOrder?'<button data-command="CANCEL_PENDING" class="danger">لغو Pending</button>':'<button data-command="MOVE_SL_TO_ENTRY" class="safe">Break Even</button><button data-command="PARTIAL_CLOSE">Partial Close</button><button data-command="ACTIVATE_TRAILING">Trailing</button><button data-command="UPDATE_SL">تغییر SL</button><button data-command="UPDATE_TP">تغییر TP</button><button data-command="CLOSE_SIGNAL" class="danger">بستن معامله</button>'}</div>`:'';return `<article class="card"><div class="card-head"><strong>${esc(p.symbol||'—')} · ${esc(p.direction||p.type||'')}</strong><span class="status">${isOrder?'PENDING':'LIVE'}</span></div><div class="levels admin-position-levels"><span>TICKET<b>${esc(p.ticket||'—')}</b></span><span>ENTRY<b>${esc(p.entry_price||p.price_open||'—')}</b></span><span>CURRENT<b>${esc(p.current_price||'—')}</b></span><span>VOLUME<b>${esc(p.volume||'—')}</b></span><span>P&amp;L<b class="${profit>0?'profit':profit<0?'loss':'flat'}">${signed(profit)}</b></span><span>SL / TP<b>${esc(p.stop_loss||'—')} / ${esc(p.take_profit||'—')}</b></span></div><div class="admin-position-sync">Last MT5 Sync: ${age==null?'—':esc(age+'s ago')}</div>${actions}</article>`}
  async function sendCommand(button){const box=button.closest('.trade-actions'),command=button.dataset.command;let value=null;if(['UPDATE_SL','UPDATE_TP','PARTIAL_CLOSE'].includes(command)){value=prompt(command==='PARTIAL_CLOSE'?'درصد یا حجم Partial Close را وارد کنید:':'مقدار جدید را وارد کنید:');if(value===null||!String(value).trim())return}if(['CLOSE_SIGNAL','CANCEL_PENDING'].includes(command)&&!confirm('این عملیات روی MT5 اجرا می‌شود. ادامه می‌دهید؟'))return;button.disabled=true;try{await api(`/signals/${box.dataset.signal}/command`,{method:'POST',body:JSON.stringify({command,account_number:box.dataset.account,value})});toast('فرمان در صف اجرای MT5 ثبت شد.')}catch(e){toast(e.message)}finally{button.disabled=false}}
  async function loadPositions(){try{const d=await api('/positions');setMt5(d.mt5_admin);const all=[...d.positions.map(x=>positionCard(x)),...d.orders.map(x=>positionCard(x,true))];$('positionList').innerHTML=all.join('')||'<div class="empty">پوزیشن یا سفارش فعال وجود ندارد.</div>';$('positionCount').textContent=fa(all.length)}catch(e){toast(e.message)}}
  document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>show(b.dataset.view));
  document.querySelectorAll('.direction button').forEach(b=>b.onclick=()=>{state.side=b.dataset.side;document.querySelectorAll('.direction button').forEach(x=>x.classList.toggle('selected',x===b));recalculate()});
  document.querySelectorAll('.destination button').forEach(b=>b.onclick=()=>{state.destination=b.dataset.value;document.querySelectorAll('.destination button').forEach(x=>x.classList.toggle('selected',x===b))});
  document.querySelectorAll('.setup-mode button').forEach(b=>b.onclick=()=>{state.setupMode=b.dataset.mode;document.querySelectorAll('.setup-mode button').forEach(x=>x.classList.toggle('selected',x===b));syncModeUI()});
  document.querySelectorAll('.volume-mode button').forEach(b=>b.onclick=()=>{state.volumeMode=b.dataset.volume;document.querySelectorAll('.volume-mode button').forEach(x=>x.classList.toggle('selected',x===b));syncModeUI()});
  ['symbol','entry','stopLoss'].forEach(id=>$(id).addEventListener('input',()=>{clearTimeout(window.__calc);window.__calc=setTimeout(recalculate,250)}));
  $('signalForm').onsubmit=e=>{e.preventDefault();openPreview()};$('publish').onclick=publish;$('recalculatePreview').onclick=()=>{$('modal').hidden=true;recalculate()};$('newSignal').onclick=()=>show('create');$('refresh').onclick=bootstrap;$('reloadSignals').onclick=loadSignals;$('reloadPositions').onclick=loadPositions;$('closeModal').onclick=$('cancelPreview').onclick=()=>{$('modal').hidden=true};
  $('positionList').addEventListener('click',event=>{const button=event.target.closest('button[data-command]');if(button)sendCommand(button)});
  ['signalList','logList'].forEach(id=>$(id).addEventListener('click',event=>{const button=event.target.closest('.retry-signal');if(button)retrySignal(button)}));
  syncModeUI();bootstrap();setInterval(()=>{if(document.visibilityState!=='visible')return;loadSignals();if(document.querySelector('#positions.view.active'))loadPositions()},5000);
})();
