(() => {
  const tg = window.Telegram?.WebApp;
  tg?.ready(); tg?.expand();
  const API = '/miniapp/api/admin';
  const state = { side: 'BUY', destination: 'BOTH', calculation: null, mt5: null, preview: null };
  const $ = (id) => document.getElementById(id);
  const headers = () => ({'Content-Type':'application/json', ...(tg?.initData ? {'X-Telegram-Init-Data':tg.initData} : {})});
  async function api(path, options={}) { const response=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}}); const body=await response.json().catch(()=>({})); if(!response.ok) throw new Error(body.detail||'خطا در ارتباط با سرور'); return body; }
  function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600)}
  function fa(value){return new Intl.NumberFormat('fa-IR',{maximumFractionDigits:8}).format(Number(value||0))}
  function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('selected',x.dataset.view===view));if(view==='positions')loadPositions();if(view==='logs')loadSignals()}
  function setMt5(mt5){state.mt5=mt5;const chip=$('mt5Chip');chip.className='chip '+(mt5?.online?'online':'offline');chip.querySelector('span').textContent=mt5?.online?'MT5 متصل':'MT5 آفلاین'}
  async function bootstrap(){try{const data=await api('/bootstrap');setMt5(data.mt5_admin);await Promise.all([loadSignals(),loadPositions()])}catch(e){toast(e.message);$('signalList').innerHTML='<div class="empty">این صفحه فقط از داخل تلگرام و برای ادمین‌های مجاز فعال است.</div>'}}
  async function recalculate(){const entry=Number($('entry').value),stop=Number($('stopLoss').value);if(!entry||!stop)return;try{const calc=await api('/signals/calculate',{method:'POST',body:JSON.stringify({symbol:$('symbol').value,direction:state.side,entry,stop_loss:stop})});state.calculation=calc;$('riskBox').querySelector('b').textContent=fa(calc.risk);$('targets').innerHTML=calc.targets.map((x,i)=>`<article><small>TP${i+1} · ${calc.target_multipliers[i]}R</small><b>${fa(x)}</b></article>`).join('')}catch(e){state.calculation=null;$('targets').innerHTML=`<p>${e.message}</p>`}}
  function requestId(){return `tg-${tg?.initDataUnsafe?.user?.id||'admin'}-${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`}
  function openPreview(){const c=state.calculation;if(!c)return toast('ابتدا مقادیر معتبر Entry و Stop Loss وارد کنید.');state.preview={symbol:c.symbol,direction:c.direction,entry:c.entry,stop_loss:c.stop_loss,risk:c.risk,targets:c.targets,destination:state.destination,timeframe:$('timeframe').value,request_id:requestId(),digits:c.digits};$('preview').innerHTML=`<div class="preview-hero"><strong>${c.symbol}</strong><em>${c.direction}</em></div><div class="preview-grid"><div><span>ورود</span><b>${fa(c.entry)}</b></div><div><span>حد ضرر</span><b>${fa(c.stop_loss)}</b></div><div><span>ریسک</span><b>${fa(c.risk)}</b></div><div><span>مقصد</span><b>${state.destination}</b></div>${c.targets.map((x,i)=>`<div><span>TP${i+1} · ${c.target_multipliers[i]}R</span><b>${fa(x)}</b></div>`).join('')}<div><span>وضعیت MT5 Admin</span><b>${state.mt5?.online?'ONLINE':'OFFLINE · WAITING'}</b></div></div>`;$('modal').hidden=false}
  async function publish(){if(!state.preview)return;const button=$('publish');button.disabled=true;button.textContent='در حال ثبت امن…';try{const result=await api('/signals',{method:'POST',body:JSON.stringify(state.preview)});$('modal').hidden=true;toast(result.status==='WAITING_FOR_MT5'?'ثبت شد؛ منتظر اتصال MT5 است.':'درخواست برای MT5 ارسال شد.');show('logs');await loadSignals()}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent='ارسال به MT5'}}
  function signalCard(item){const p=JSON.parse(item.payload_json||'{}'),job=String(item.chart_job?.status||'').toUpperCase(),stage=String(item.signal?.publication_stage||'').toUpperCase();const retryable=['FAILED','PUBLISH_FAILED','EXPIRED'].includes(String(item.status).toUpperCase())||(['UPLOADED','COMPLETED'].includes(job)&&item.status!=='PUBLISHED'&&stage!=='PUBLISHED');const retry=retryable?`<button class="outline retry-signal" data-request-id="${esc(item.request_id)}">تلاش مجدد</button>`:'';return `<article class="card"><div class="card-head"><strong>${p.symbol||item.signal?.symbol||'—'} · ${p.direction||''}</strong><span class="status ${item.status}">${item.status}</span></div><div class="levels"><span>ENTRY<b>${p.entry||'—'}</b></span><span>SL<b>${p.stop_loss||'—'}</b></span><span>DEST<b>${p.destination||'—'}</b></span></div>${item.error_message?`<p style="color:var(--red);font-size:10px">${esc(item.error_message)}</p>`:''}${retry}</article>`}
  async function retrySignal(button){button.disabled=true;try{const result=await api(`/signals/${encodeURIComponent(button.dataset.requestId)}/retry`,{method:'POST'});toast(result.publication==='RETRY_QUEUED'?'انتشار مجدد در صف قرار گرفت.':'درخواست همان سیگنال احیا شد.');await loadSignals()}catch(e){toast(e.message)}finally{button.disabled=false}}
  async function loadSignals(){try{const data=await api('/signals');setMt5(data.mt5_admin);$('signalList').innerHTML=data.items.length?data.items.map(signalCard).join(''):'<div class="empty">هنوز سیگنالی صادر نشده است.</div>';$('logList').innerHTML=data.items.length?data.items.map(signalCard).join(''):'<div class="empty">لاگی وجود ندارد.</div>';$('openCount').textContent=fa(data.items.filter(x=>!['PUBLISHED','FAILED'].includes(x.status)).length);$('waitingCount').textContent=fa(data.items.filter(x=>x.status==='WAITING_FOR_MT5').length)}catch(e){toast(e.message)}}
  function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
  function positionCard(p,isOrder=false){const signalId=Number(p.signal_id||0),account=esc(state.mt5?.account_number||'');const actions=signalId?`<div class="trade-actions" data-signal="${signalId}" data-account="${account}">${isOrder?'<button data-command="CANCEL_PENDING" class="danger">لغو Pending</button>':'<button data-command="MOVE_SL_TO_ENTRY" class="safe">Break Even</button><button data-command="PARTIAL_CLOSE">Partial Close</button><button data-command="ACTIVATE_TRAILING">Trailing</button><button data-command="UPDATE_SL">تغییر SL</button><button data-command="UPDATE_TP">تغییر TP</button><button data-command="CLOSE_SIGNAL" class="danger">بستن معامله</button>'}</div>`:'';return `<article class="card"><div class="card-head"><strong>${esc(p.symbol||'—')} · ${esc(p.direction||p.type||'')}</strong><span class="status">${isOrder?'PENDING':'LIVE'}</span></div><div class="levels"><span>TICKET<b>${esc(p.ticket||'—')}</b></span><span>ENTRY<b>${esc(p.entry_price||p.price_open||'—')}</b></span><span>VOLUME<b>${esc(p.volume||'—')}</b></span></div>${actions}</article>`}
  async function sendCommand(button){const box=button.closest('.trade-actions'),command=button.dataset.command;let value=null;if(['UPDATE_SL','UPDATE_TP','PARTIAL_CLOSE'].includes(command)){value=prompt(command==='PARTIAL_CLOSE'?'درصد یا حجم Partial Close را وارد کنید:':'مقدار جدید را وارد کنید:');if(value===null||!String(value).trim())return}if(['CLOSE_SIGNAL','CANCEL_PENDING'].includes(command)&&!confirm('این عملیات روی MT5 اجرا می‌شود. ادامه می‌دهید؟'))return;button.disabled=true;try{await api(`/signals/${box.dataset.signal}/command`,{method:'POST',body:JSON.stringify({command,account_number:box.dataset.account,value})});toast('فرمان در صف اجرای MT5 ثبت شد.')}catch(e){toast(e.message)}finally{button.disabled=false}}
  async function loadPositions(){try{const data=await api('/positions');setMt5(data.mt5_admin);const all=[...data.positions.map(x=>positionCard(x)),...data.orders.map(x=>positionCard(x,true))];$('positionList').innerHTML=all.join('')||'<div class="empty">پوزیشن یا سفارش فعال وجود ندارد.</div>';$('positionCount').textContent=fa(all.length)}catch(e){toast(e.message)}}
  document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>show(b.dataset.view));
  document.querySelectorAll('.direction button').forEach(b=>b.onclick=()=>{state.side=b.dataset.side;document.querySelectorAll('.direction button').forEach(x=>x.classList.toggle('selected',x===b));recalculate()});
  document.querySelectorAll('.destination button').forEach(b=>b.onclick=()=>{state.destination=b.dataset.value;document.querySelectorAll('.destination button').forEach(x=>x.classList.toggle('selected',x===b))});
  ['symbol','entry','stopLoss'].forEach(id=>$(id).addEventListener('input',()=>{clearTimeout(window.__calc);window.__calc=setTimeout(recalculate,250)}));
  $('signalForm').onsubmit=e=>{e.preventDefault();openPreview()};$('publish').onclick=publish;$('newSignal').onclick=()=>show('create');$('refresh').onclick=bootstrap;$('reloadSignals').onclick=loadSignals;$('reloadPositions').onclick=loadPositions;
  $('closeModal').onclick=$('cancelPreview').onclick=()=>{$('modal').hidden=true};
  $('positionList').addEventListener('click',event=>{const button=event.target.closest('button[data-command]');if(button)sendCommand(button)});
  ['signalList','logList'].forEach(id=>$(id).addEventListener('click',event=>{const button=event.target.closest('.retry-signal');if(button)retrySignal(button)}));
  bootstrap(); setInterval(()=>{if(document.visibilityState==='visible')loadSignals()},5000);
})();
